//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOfferBrowser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Collector()
        {
            this.CollectorName = new ObservableListSource<CollectorName>();
            this.OfferItemCollector = new ObservableListSource<OfferItemCollector>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AvatarID { get; set; }
        public byte[] timestamp { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public Nullable<int> DefaultCategoryId { get; set; }
        public bool StockRelated { get; set; }
        public bool LedgerRelated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<CollectorName> CollectorName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<OfferItemCollector> OfferItemCollector { get; set; }
    }
}
