//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOfferBrowser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.VoucherAddress = new ObservableListSource<VoucherAddress>();
        }
    
        public int PartnerId { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string LanguageId { get; set; }
        public bool RealAddrInherited { get; set; }
        public string RealCountryId { get; set; }
        public string RealStreet { get; set; }
        public string RealCity { get; set; }
        public string RealRegion { get; set; }
        public string RealZip { get; set; }
        public string RealAddress { get; set; }
        public bool PostAddrReal { get; set; }
        public bool PostAddrInherited { get; set; }
        public string PostCountryId { get; set; }
        public string PostStreet { get; set; }
        public string PostCity { get; set; }
        public string PostRegion { get; set; }
        public string PostZip { get; set; }
        public string PostAddress { get; set; }
        public string Description { get; set; }
        public string GLN { get; set; }
        public string ExciseAuthorisationNumber { get; set; }
        public bool InvoiceAddress { get; set; }
        public bool InvoicePostAddress { get; set; }
        public string VoucherName { get; set; }
        public string RealDistrict { get; set; }
        public string RealPublicPlaceName { get; set; }
        public string RealPublicPlaceKind { get; set; }
        public string RealPublicPlaceNumber { get; set; }
        public string RealBuilding { get; set; }
        public string RealStairWay { get; set; }
        public string RealStorey { get; set; }
        public string RealDoorNumber { get; set; }
    
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<VoucherAddress> VoucherAddress { get; set; }
    }
}
