//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOfferBrowser
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileStore()
        {
            this.OfferVersion = new ObservableListSource<OfferVersion>();
        }
    
        public int Id { get; set; }
        public byte[] timestamp { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<int> SrcAvatarId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int AccessLevelId { get; set; }
        public bool IsGenerated { get; set; }
        public bool IsArchiveable { get; set; }
        public bool IsArchived { get; set; }
        public string Name { get; set; }
        public string OriginalName { get; set; }
        public Nullable<System.DateTime> OriginalDate { get; set; }
        public string FileExtension { get; set; }
        public string ODMAID { get; set; }
        public string ArchiveDb { get; set; }
        public string Keywords { get; set; }
        public string LinkedText { get; set; }
        public byte[] FileContent { get; set; }
        public Nullable<bool> IsSigned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<OfferVersion> OfferVersion { get; set; }
    }
}
