//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOfferBrowser
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferItemCollector
    {
        public int OfferItemId { get; set; }
        public int CollectorId { get; set; }
        public decimal Amount { get; set; }
        public decimal Percent { get; set; }
        public bool IsPercent { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public bool StockRelated { get; set; }
        public bool LedgerRelated { get; set; }
    
        public virtual Collector Collector { get; set; }
        public virtual OfferItem OfferItem { get; set; }
    }
}
