//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOfferBrowser
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Data.Entity;
    
    public partial class Offer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offer()
        {
            this.OfferVersion = new ObservableListSource<OfferVersion>();
        }
    
        public int Id { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<int> AvatarId { get; set; }
        public int OfferFileId { get; set; }
        public int OrdinalNumber { get; set; }
        public Nullable<int> AgentPartnerId { get; set; }
        public Nullable<int> SrcProjectId { get; set; }
        public Nullable<int> MarketingChannelId { get; set; }
        public string VoucherNum { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> ResponsibleEmployeeId { get; set; }
        public bool BruttoCalcMode { get; set; }
        public string HeadNote { get; set; }
        public string FootNote { get; set; }
        public string LanguageId { get; set; }
        public Nullable<int> TransactionTypeId { get; set; }
        public Nullable<int> OutputFormat { get; set; }
        public Nullable<int> InputFormat { get; set; }
        public int CancellationState { get; set; }
        public string InCoTermId { get; set; }
        public string InCoTermSrc { get; set; }
        public string InCoTermDst { get; set; }
        public string InCoTermDocNr { get; set; }
        public Nullable<int> TransportModeId { get; set; }
        public string Name { get; set; }
    
        public virtual OfferFile OfferFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<OfferVersion> OfferVersion { get; set; }

        public IList<int> GetTypeIdDistinct(DbSet<Offer> Offer)
        {
            IList<int> result;
            result = (from o in Offer select TypeId).Distinct().ToList();

            return result;
                              
        }

    }
}
