//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOfferBrowser
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfferVersion()
        {
            this.OfferVersionGroup = new ObservableListSource<OfferVersionGroup>();
        }
    
        public int Id { get; set; }
        public int OfferId { get; set; }
        public int Version { get; set; }
        public int StatusId { get; set; }
        public System.DateTime VersionDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> ImageFileStoreId { get; set; }
        public Nullable<int> PriceTypeId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<decimal> DefaultDiscountPercent { get; set; }
    
        public virtual FileStore FileStore { get; set; }
        public virtual Offer Offer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<OfferVersionGroup> OfferVersionGroup { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual PriceType PriceType { get; set; }
    }
}
