//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOfferBrowser
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferFileNote
    {
        public int OfferFileId { get; set; }
        public string LanguageId { get; set; }
        public string HeadNote { get; set; }
        public string FootNote { get; set; }
    
        public virtual OfferFile OfferFile { get; set; }
    }
}
