//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOfferBrowser
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferVersionGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfferVersionGroup()
        {
            this.OfferItem = new ObservableListSource<OfferItem>();
        }
    
        public int Id { get; set; }
        public int OfferVersionId { get; set; }
        public string Name { get; set; }
        public bool IsDefault { get; set; }
        public string HeadNote { get; set; }
        public string FootNote { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<decimal> BaseAmount { get; set; }
        public Nullable<decimal> BaseTax { get; set; }
        public Nullable<decimal> BaseTotal { get; set; }
        public Nullable<decimal> OffAmount { get; set; }
        public Nullable<decimal> OffTax { get; set; }
        public Nullable<decimal> OffTotal { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> PrepaymentNeeded { get; set; }
        public Nullable<decimal> PrepaymentAmount { get; set; }
        public Nullable<decimal> PrepaymentPercent { get; set; }
        public Nullable<bool> PrepaymentIsPercent { get; set; }
        public Nullable<int> PrepaymentId { get; set; }
        public string InvoiceCurrencyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<OfferItem> OfferItem { get; set; }
        public virtual OfferVersion OfferVersion { get; set; }
    }
}
