//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOfferBrowser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.Department = new ObservableListSource<Department>();
            this.Offer = new ObservableListSource<Offer>();
            this.PartnerClientNo = new ObservableListSource<PartnerClientNo>();
            this.Product = new ObservableListSource<Product>();
        }
    
        public int Id { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<int> AvatarId { get; set; }
        public string Name { get; set; }
        public int PaymentId { get; set; }
        public int PriceTypeId { get; set; }
        public Nullable<int> PartNoId { get; set; }
        public string DefaultCurrencyId { get; set; }
        public string DefaultEcoTaxCode { get; set; }
        public bool VatRegistated { get; set; }
        public bool CashAccounting { get; set; }
        public bool DelayCostLump { get; set; }
        public bool Inactive { get; set; }
        public Nullable<System.DateTime> ReceivesEInvoiceFrom { get; set; }
        public Nullable<System.DateTime> ReceivesEInvoiceTo { get; set; }
        public Nullable<System.DateTime> SendsEInvoiceFrom { get; set; }
        public Nullable<System.DateTime> SendsEInvoiceTo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Department> Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Offer> Offer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<PartnerClientNo> PartnerClientNo { get; set; }
        public virtual PartNo PartNo { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual PriceType PriceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Product> Product { get; set; }
    }
}
