//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOfferBrowser
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerClientNo
    {
        public int PartnerId { get; set; }
        public int ClientNoId { get; set; }
        public string Value { get; set; }
    
        public virtual Partner Partner { get; set; }
    }
}
