//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOfferBrowser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OfferItem = new ObservableListSource<OfferItem>();
            this.ProductName = new ObservableListSource<ProductName>();
            this.ProductPartNo = new ObservableListSource<ProductPartNo>();
        }
    
        public int Id { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<int> AvatarId { get; set; }
        public string CurrencyId { get; set; }
        public string StockCurrencyId { get; set; }
        public Nullable<int> MeasureId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public bool StockManagement { get; set; }
        public Nullable<decimal> NetMass { get; set; }
        public Nullable<decimal> BrtMass { get; set; }
        public decimal MassQty { get; set; }
        public decimal PriceQty { get; set; }
        public string IntrastatCtId { get; set; }
        public int Identification { get; set; }
        public bool IdentOnOut { get; set; }
        public int ProductRevenuesGroupId { get; set; }
        public int ProductBookingGroupId { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> CostPriceRate { get; set; }
        public bool ExciseMonitoring { get; set; }
        public bool EcoTaxContainer { get; set; }
        public string Note { get; set; }
        public bool ValidDateNecessaryOnInput { get; set; }
        public Nullable<int> DefaultSupplier { get; set; }
        public int BarcodeLabelCopies { get; set; }
        public Nullable<int> PackagingMeasureId { get; set; }
        public decimal PackagingQuantity { get; set; }
        public bool PackageIsOpenable { get; set; }
        public bool StandardCosting { get; set; }
        public int Colli { get; set; }
        public string BAFCN { get; set; }
        public bool OutOfIntrastat { get; set; }
        public Nullable<int> SecondaryMeasureId { get; set; }
        public int SecondaryMeasureUsage { get; set; }
        public bool Mediated { get; set; }
    
        public virtual Measure Measure { get; set; }
        public virtual Measure Measure1 { get; set; }
        public virtual Measure Measure2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<OfferItem> OfferItem { get; set; }
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<ProductName> ProductName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<ProductPartNo> ProductPartNo { get; set; }
    }
}
