//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOfferBrowser
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductName
    {
        public int ProductId { get; set; }
        public string LanguageId { get; set; }
        public string Value { get; set; }
        public string Note { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
