//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOfferBrowser
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPartNo
    {
        public int ProductId { get; set; }
        public int PartNoId { get; set; }
        public string Value { get; set; }
    
        public virtual PartNo PartNo { get; set; }
        public virtual Product Product { get; set; }
    }
}
