//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOfferBrowser
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalesOfferEntities : DbContext
    {
        public SalesOfferEntities()
            : base("name=SalesOfferEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Channel> Channel { get; set; }
        public virtual DbSet<ChannelPrintName> ChannelPrintName { get; set; }
        public virtual DbSet<Collector> Collector { get; set; }
        public virtual DbSet<CollectorName> CollectorName { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<FileStore> FileStore { get; set; }
        public virtual DbSet<Measure> Measure { get; set; }
        public virtual DbSet<MeasureSign> MeasureSign { get; set; }
        public virtual DbSet<Offer> Offer { get; set; }
        public virtual DbSet<OfferFile> OfferFile { get; set; }
        public virtual DbSet<OfferFileNote> OfferFileNote { get; set; }
        public virtual DbSet<OfferFileReport> OfferFileReport { get; set; }
        public virtual DbSet<OfferItem> OfferItem { get; set; }
        public virtual DbSet<OfferItemCollector> OfferItemCollector { get; set; }
        public virtual DbSet<OfferItemProperty> OfferItemProperty { get; set; }
        public virtual DbSet<OfferItemSchedule> OfferItemSchedule { get; set; }
        public virtual DbSet<OfferLinkOffer> OfferLinkOffer { get; set; }
        public virtual DbSet<OfferVersion> OfferVersion { get; set; }
        public virtual DbSet<OfferVersionGroup> OfferVersionGroup { get; set; }
        public virtual DbSet<Partner> Partner { get; set; }
        public virtual DbSet<PartnerClientNo> PartnerClientNo { get; set; }
        public virtual DbSet<PartNo> PartNo { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<PaymentPrintName> PaymentPrintName { get; set; }
        public virtual DbSet<PriceType> PriceType { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductName> ProductName { get; set; }
        public virtual DbSet<ProductPartNo> ProductPartNo { get; set; }
        public virtual DbSet<VoucherAddress> VoucherAddress { get; set; }
        public virtual DbSet<VoucherAddressChannel> VoucherAddressChannel { get; set; }
        public virtual DbSet<VoucherAddressClientNo> VoucherAddressClientNo { get; set; }
    }
}
